### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by BigFlubba** [pikaioff/USERPFP#2]
I was wondering where the custom pfp shows up? Does it show up on the account page in the settings? Also, does this also allow for nitro subscribers for us to also see their customs and nitro pfp's?
![image](https://user-images.githubusercontent.com/69104450/175643470-5c153109-d78d-48ee-84c9-351c1d1c32c0.png)

How would this snippet be converted to the custom pfp's if it does support seeing the custom and nitro pfp's?
```css
/* Adjusts the appearance of and adds hover/transition effects to UserBackgrounds badges */
.UserBackgrounds-banner-badge {
  background-color: rgba(32, 34, 37, 0.8) !important;
  font-size: 11px;
  opacity: 0;
  transform: matrix(1, 0, 0, 1, 0, 5);
  transition-delay: 0s, 0s, 0s;
  transition-duration: 0.15s, 0.15s, 0.15s;
  transition-property: opacity, transform;
  transition-timing-function: ease-out, ease-out, ease-out;
}
.UserBackgrounds-banner-container:hover .UserBackgrounds-banner-badge {
  opacity: 1;
  transform: matrix(1, 0, 0, 1, 0, 0);
}
.UserBackgrounds-banner-arrow {
  opacity: 0 !important;
  transform: matrix(1, 0, 0, 1, 0, -5);
  transition-delay: 0s, 0s, 0s;
  transition-duration: 0.15s, 0.15s, 0.15s;
  transition-property: opacity, transform;
  transition-timing-function: ease-out, ease-out, ease-out;
}
.UserBackgrounds-banner-container:hover .UserBackgrounds-banner-arrow:not([disabled]) {
  opacity: 1 !important;
  transform: matrix(1, 0, 0, 1, 0, 0);
}
.UserBackgrounds-banner-container:hover .UserBackgrounds-banner-arrow[disabled] {
  opacity: 0.5 !important;
  transform: matrix(1, 0, 0, 1, 0, 0);
}
.accountProfileCard-lbN7n- .UserBackgrounds-banner-badge {
  display: none !important;
}
```
